### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by iamChenyin** [haren724/open-wallpaper-engine-mac#10]
1.在导入多张壁纸时无法切换壁纸
2.在呼出设置和筛选结果菜单时会出现黑屏的情况
3.某些视频壁纸无法识别

设备：DELL灵越5570
系统：MacOS13
版本：0.1.0

**Comment by qbmzc** [comment]
第3个问题，看下project.json中是不是缺少了description，加上就可以识别了。这个应该需要修复一下

**Comment by haren724** [comment]
> 第3个问题，看下project.json中是不是缺少了description，加上就可以识别了。这个应该需要修复一下

也就是说有些壁纸不一定有description是吧，我下载的壁纸里面都有这个键，所以我就把它的类型设置成String了。

如果确定确实有的壁纸压根就没有description（如果仅仅是description的值为空不算）的话，我就把它的类型改成String?

**Comment by qbmzc** [comment]
> 

是的，我导出来的有些工程里面是没有这个的，因为这个在wallpaper engine中并不是必填项

**Comment by qbmzc** [comment]
> > 第3个问题，看下project.json中是不是缺少了description，加上就可以识别了。这个应该需要修复一下
> 
> 也就是说有些壁纸不一定有description是吧，我下载的壁纸里面都有这个键，所以我就把它的类型设置成String了。
> 
> 如果确定确实有的壁纸压根就没有description（如果仅仅是description的值为空不算）的话，我就把它的类型改成String?

是的，我导出来的有些工程里面是没有这个的，因为这个在wallpaper engine中并不是必填项

**Comment by Toby-Shi-cloud** [comment]
另外 `tags` 也不是必须有的。
所以可以考虑 `var tags: [String]?`

**Comment by haren724** [comment]
已修改👌
