### ISSUE TITLE
视频壁纸播放完成后会闪屏

### ISSUE THREAD

**Issue by Doramifa** [haren724/open-wallpaper-engine-mac#13]
导入视频壁纸之后，每次循环开始的时候会黑屏闪烁一下

**Comment by Doramifa** [comment]
M1 pro ， mac os 14.0 Beta

**Comment by haren724** [comment]
You're right. 

Currently the viewModels in this app are not being constructed so well. It leads Wallpapers Player reset its `AVPlayer` property every time any property changed in the viewModel.

BTW, this issue doesn't cause app to crash directly. I'll come up with a better viewModel management method to solve this later on.

**Comment by haren724** [comment]
闪屏问题已解决 391d75b9b70411f03d216537a8a9acc25da0b975

感谢你的反馈
