### ISSUE TITLE
导入壁纸侧边栏变为壁纸封面

### ISSUE THREAD

**Issue by Win10Q** [haren724/open-wallpaper-engine-mac#14]
![上传0d1f2386606175a516dde447e174b61e.png...]()
如上图这样导入后边栏无法使用变为壁纸封面

**Comment by haren724** [comment]
Seems like this issue is caused by the same reason as #2.

 If you believe this issue has not been solved in the next release, please create a new issue. 

Thanks.

**Comment by haren724** [comment]
Duplicate of #2
