### ISSUE TITLE
播放带有音频的壁纸时”参数设置“的音量对壁纸无效

### ISSUE THREAD

**Issue by baysonfox** [haren724/open-wallpaper-engine-mac#18]
**描述错误**
在侧栏的参数设置中将音量调整到0.0后，壁纸音频依然不会被静音

**重现过程**
重现触发bug的步骤：
1. 播放一个带有音频的壁纸
2. 在侧栏的设置中调整音量

**预期行为**
壁纸播放的音频被静音

**Desktop (please complete the following information):**
 - OS: macOS Sonoma (23A5312d)
 - Version: git clone 的源代码

**附加内容**
似乎调整音量的时候会出现两个音频，一个可以被参数设置的音量控制，另一个无法被控制.

**Comment by haren724** [comment]
感谢反馈！请问你拉取了这个commit吗 9ae99a3b5fb89623a4687d15145a3c549eb6f7b9

<img width="626" alt="Screenshot 2023-08-27 at 10 35 52" src="https://github.com/haren724/open-wallpaper-engine-mac/assets/61335850/cf192b37-1832-46f2-bfd8-de1146ceb43e">

如果这个版本问题依然存在，请告诉我

**Comment by baysonfox** [comment]
问题依然存在.
<img width="151" alt="image" src="https://github.com/haren724/open-wallpaper-engine-mac/assets/23008133/b14308be-22e7-4abb-93bb-42b0fe5d63e9">
<img width="804" alt="image" src="https://github.com/haren724/open-wallpaper-engine-mac/assets/23008133/223aaa67-2843-4bf6-9e51-6b48e1717cc0">

**Comment by haren724** [comment]
麻烦把你的壁纸文件夹上传到这里来吧：https://www.icloud.com.cn/iclouddrive/0016GAsVHK8S1t6GKF6Enty7A#Wallpapers

我看看是不是视频格式的问题

**Comment by baysonfox** [comment]
已经传上去了，在`3012918464/`

**Comment by haren724** [comment]
这个问题应该解决了，如果仍然有类似问题出现，请提交一个新的issue❤️
