### ISSUE TITLE
README 的Build 有一点小问题

### ISSUE THREAD

**Issue by Toby-Shi-cloud** [haren724/open-wallpaper-engine-mac#19]
**描述错误**
README 的 第86行 使用 XCODE 打开有笔误
[`open open-wallpaper-engine-mac -a /Application/Xcode.app`](https://github.com/haren724/open-wallpaper-engine-mac/blob/391d75b9b70411f03d216537a8a9acc25da0b975/README.md?plain=1#L86C1-L86C57)

这里应该是 `open open-wallpaper-engine-mac -a /Applications/Xcode.app`

即应该为 `Applications` 而非 `Application`

这是个小错误，大佬有空就顺便改了吧？

**Comment by Toby-Shi-cloud** [comment]
似乎 README 其他地方也写的是 `/Application`，但不知道是不是 macOS 版本的关系，我的应用程序在 `/Applications` 目录下。

**Comment by haren724** [comment]
OK，感谢指正🤝 在 7c56a5fd10b45f7cbe7dd0fa6398baaeea94dc3c 中已解决
