### ISSUE TITLE
GifImage的View在macOS13会导致程序崩溃

### ISSUE THREAD

**Issue by dawalishi0821** [haren724/open-wallpaper-engine-mac#2]
GifImage的View在macOS13会导致程序崩溃
---
以下是报错日志：

Engine[23897:171509] -[NSNib _initWithNibNamed:bundle:options:] could not load the nibName: Open_Wallpaper_Engine.WallpaperViewController in bundle NSBundle </Users/yujiale/Library/Developer/Xcode/DerivedData/Open_Wallpaper_Engine-bxsqphaeozfylefxrsanvmmodibt/Build/Products/Debug/Open Wallpaper Engine.app> (loaded).

**Comment by haren724** [comment]
的确如此，复现出来了。在分支提交 ab782fa35787fdbbf2585423ac5b7a0f6c24543f 中已经暂时禁用，未来等功能完善之后再重新启用

**Comment by haren724** [comment]
This issue which is about GifImage is finally solved at commit 4787f60040bd775b2200b9390bf8f49e81034c77. Thanks for your help!
