### ISSUE TITLE
桌面背景动态壁纸窗口无法显示

### ISSUE THREAD

**Issue by dawalishi0821** [haren724/open-wallpaper-engine-mac#3]
桌面背景动态壁纸窗口无法显示

![image](https://github.com/haren724/open-wallpaper-engine-mac/assets/112949492/9d25c7e7-54a4-4a6e-b26a-bc3db2fdb205)

**Comment by haren724** [comment]
你好，分支提交 579caeb0bd12b58b50edc4ed7784a7669d223c5a 应该已经解决了这个问题，可以尝试一下哦
